version: "{branch}-{build}"
test: off

os:
  - Visual Studio 2015

platform:
#  - x86
  - x64

configuration:
#  - Debug
#  - Release
  - RelWithDebInfo

install:
  - cinst doxygen.portable

init:
  - if %platform%==x64 (set CMAKE_PREFIX_PATH=C:\Qt\5.10.1\msvc2015_64) else (set CMAKE_PREFIX_PATH=C:\Qt\5.10.1\msvc2015)
  - if %platform%==x64 (set generator=Visual Studio 14 2015 Win64) else (set generator=Visual Studio 14 2015)
  - if %platform%==x64 (set msplatform=x64) else (set msplatform=Win32)

before_build:
  - md build
  - cd build

build_script:
  - echo "Platform      = %platform%"
  - echo "MS Platform   = %msplatform%"
  - echo "Configuration = %configuration%"
  - echo "Generator     = %generator%"
  - appveyor DownloadFile https://github.com/comphack/external/releases/download/external-16/external-0.1.1-win64.zip -FileName external.zip
  - 7z x external.zip
  - del external.zip
  - mv external* ..\binaries
  - cmake -DGENERATE_DOCUMENTATION=ON -DWINDOWS_SERVICE=ON -DCMAKE_INSTALL_PREFIX="%appveyor_build_folder%\build\install" -DCMAKE_CUSTOM_CONFIGURATION_TYPES="%configuration%" -G"%generator%" ..
  - cmake --build . --config %configuration% --target package
  - cmake --build . --config %configuration% --target doc
  - 7z a comp_hack-api.zip api

artifacts:
  - path: build\comp_hack-*.msi
    name: comp_hack_installer
  - path: build\comp_hack-*.zip
    name: comp_hack_archive
