version: "{branch}-{build}"
test: off

os:
  - Visual Studio 2015

platform:
  - x86
  - x64

configuration:
#  - Debug
#  - Release
  - RelWithDebInfo

install:
  - cinst graphviz.portable

init:
  - if %platform%==x64 (set CMAKE_PREFIX_PATH=C:\Qt\5.10.1\msvc2015_64) else (set CMAKE_PREFIX_PATH=C:\Qt\5.10.1\msvc2015)
  - if %platform%==x64 (set generator=Visual Studio 14 2015 Win64) else (set generator=Visual Studio 14 2015)
  - if %platform%==x64 (set msplatform=x64) else (set msplatform=Win32)

before_build:
  - md build
  - cd build

build_script:
  - echo "Platform      = %platform%"
  - echo "MS Platform   = %msplatform%"
  - echo "Configuration = %configuration%"
  - echo "Generator     = %generator%"
  - git submodule update --init --recursive
  - if %platform%==x64 (appveyor DownloadFile https://github.com/comphack/external/releases/download/external-25/external-0.1.1-win64.zip -FileName external.zip) else (appveyor DownloadFile https://github.com/comphack/external/releases/download/external-25/external-0.1.1-win32.zip -FileName external.zip)
  - 7z x external.zip
  - del external.zip
  - mv external* ..\binaries
  - if %platform%==x64 (appveyor DownloadFile https://github.com/comphack/objgen/releases/download/v1.0.1/objgen-win64.zip -FileName objgen.zip)
  - if %platform%==x64 (7z x objgen.zip)
  - if %platform%==x64 (del objgen.zip)
  - if %platform%==x64 (mv objgen* ..\deps\objgen)
  - if %platform%==x64 (appveyor DownloadFile https://github.com/comphack/libobjects/releases/download/v1.0.16/libobjects-win64.zip -FileName libobjects.zip)
  - if %platform%==x64 (7z x libobjects.zip)
  - if %platform%==x64 (del libobjects.zip)
  - if %platform%==x64 (mv libobjects* ..\deps\libobjects)
  - if %platform%==x64 (appveyor DownloadFile https://github.com/comphack/external/releases/download/external-25/doxygen-1.8.14.windows.x64.bin.zip -FileName doxygen.zip)
  - if %platform%==x64 (mkdir doxygen)
  - if %platform%==x64 (cd doxygen)
  - if %platform%==x64 (7z x ..\doxygen.zip)
  - if %platform%==x64 (cd ..)
  - if %platform%==x64 (del doxygen.zip)
  - set PATH=%APPVEYOR_BUILD_FOLDER%\build\doxygen;%PATH%
  - if %platform%==x64 (cmake -DUSE_PREBUILT_OBJECTS=ON -DGENERATE_DOCUMENTATION=ON -DWINDOWS_SERVICE=ON -DCMAKE_INSTALL_PREFIX="%appveyor_build_folder%\build\install" -DCMAKE_CUSTOM_CONFIGURATION_TYPES="%configuration%" -G"%generator%" ..) else (cmake -DUSE_PREBUILT_OBJECTS=ON -DGENERATE_DOCUMENTATION=ON -DWINDOWS_SERVICE=ON -DCMAKE_INSTALL_PREFIX="%appveyor_build_folder%\build\install" -DCMAKE_CUSTOM_CONFIGURATION_TYPES="%configuration%" -DUPDATER_ONLY=ON -G"%generator%" ..)
  - cmake --build . --config %configuration% --target package
  - if %platform%==x64 (cmake --build . --config %configuration% --target doc)
  - if %platform%==x64 (7z a comp_hack-api.zip api)

artifacts:
  - path: build\comp_hack-*.msi
    name: comp_hack_installer
  - path: build\comp_hack-*.zip
    name: comp_hack_archive
