version: "{branch}-{build}"
test: off

os:
  - Visual Studio 2015

platform:
#  - x86
  - x64

configuration:
#  - Debug
#  - Release
  - RelWithDebInfo

install:
  - cinst graphviz.portable

init:
  - if %platform%==x64 (set CMAKE_PREFIX_PATH=C:\Qt\5.10.1\msvc2015_64) else (set CMAKE_PREFIX_PATH=C:\Qt\5.10.1\msvc2015)
  - if %platform%==x64 (set generator=Visual Studio 14 2015 Win64) else (set generator=Visual Studio 14 2015)
  - if %platform%==x64 (set msplatform=x64) else (set msplatform=Win32)

before_build:
  - md build
  - cd build

build_script:
  - echo "Platform      = %platform%"
  - echo "MS Platform   = %msplatform%"
  - echo "Configuration = %configuration%"
  - echo "Generator     = %generator%"
  - git submodule update --init --recursive
  - appveyor DownloadFile https://github.com/comphack/external/releases/download/external-21/external-0.1.1-win64.zip -FileName external.zip
  - 7z x external.zip
  - del external.zip
  - mv external* ..\binaries
  - appveyor DownloadFile https://github.com/comphack/objgen/releases/download/v1.0.1/objgen-win64.zip -FileName objgen.zip
  - 7z x objgen.zip
  - del objgen.zip
  - mv objgen* ..\deps\objgen
  - appveyor DownloadFile https://github.com/comphack/libobjects/releases/download/v1.0.11/libobjects-win64.zip -FileName libobjects.zip
  - 7z x libobjects.zip
  - del libobjects.zip
  - mv libobjects* ..\deps\libobjects
  - appveyor DownloadFile http://doxygen.nl/files/doxygen-1.8.14.windows.x64.bin.zip -FileName doxygen.zip
  - mkdir doxygen
  - cd doxygen
  - 7z x ..\doxygen.zip
  - cd ..
  - del doxygen.zip
  - set PATH=%APPVEYOR_BUILD_FOLDER%\build\doxygen;%PATH%
  - cmake -DUSE_PREBUILT_OBJECTS=ON -DGENERATE_DOCUMENTATION=ON -DWINDOWS_SERVICE=ON -DCMAKE_INSTALL_PREFIX="%appveyor_build_folder%\build\install" -DCMAKE_CUSTOM_CONFIGURATION_TYPES="%configuration%" -G"%generator%" ..
  - cmake --build . --config %configuration% --target package
  - cmake --build . --config %configuration% --target doc
  - 7z a comp_hack-api.zip api

artifacts:
  - path: build\comp_hack-*.msi
    name: comp_hack_installer
  - path: build\comp_hack-*.zip
    name: comp_hack_archive
